# Generated by Django 6.0.7 on 2026-07-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DenunciaModel',
        ),
    ]
